import { Icon } from "@iconify-icon/solid"
import { A } from "@solidjs/router"
import { shortStr } from "../../lib/tool"
import { createEffect, createMemo, For, Show } from "solid-js"
import { pool,app } from "../../signals/global"
import tooltip from "../../components/tooltip"
import { state,stats } from "../../signals/pool"
import { toBalanceValue } from "../../lib/tool"
import Balls from "../../components/balls"
import Aox from "./partners/aox"
import Permaswap from "./partners/permaswap"
import Aolink from "./partners/aolink"
import Typr from "./partners/typr"
import Seagull from "./partners/seagull"
import Pattern from "../../components/pattern"
import Altlogo from "../../components/altlogo"




export default props => {
  const partners = createMemo(()=>([{
    tooltip: "The largest cross-chain bridge in the AO ecosystem, AOX enables seamless payments.",
    link: "https://aox.xyz",
    element: <Aox class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Permaswap is our strategic partner, offering DEX integration.",
    link: "https://www.permaswap.network",
    element: <Permaswap class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Aolink provides on-chain querying.",
    link: "https://www.ao.link",
    element: <Aolink class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Typr is our strategic partner, a decentralized information publishing platform like twitter.",
    link: "https://www.typr.day",
    element: <Typr class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Seagull is a partner of our ecosystem with a focus on GameFi.",
    link: "https://x.com/happytowngame",
    element: <Seagull class="opacity-50 h-8 hover:opacity-100"/>
  }]))

  const faq = createMemo(()=>([{
    title:"How dose Aolotto work?",
    content: <div class="flex flex-col gap-4">
      <p>Aolotto is a simple lottery game where players bet $1 to choose a three-digit number (000-999). A draw occurs at the end of each round, with a lucky number generated by algorithm. bets that match the number win.</p>
      <p>Winners share the accumulated jackpot proportionally based on their bet amounts. If no matching bets are placed in a round, the last player takes the entire jackpot.</p>
      <p>The accumulated jackpot consists of 50% of pool balance, while the remaining 50% becomes the base prize for the next round.</p>
      <p>Aolotto's draw time is dynamic, Each new bet extends the draw by 24 hours until the pool's accumulated bets reach the target. When draw time arrives, the game moves to the next round, and the draw is triggered at the next block height after the round ends.</p>
    </div>
  },
    {
      title:"What is the difference between aolotto and traditional lottery?",
      content:<p>Decentralized lotteries offer <b>transparency</b>, <b>fairness</b>, and <b>global accessibility</b>. Blockchain records ensure tamper-proof draws, while smart contracts eliminate fraud and intermediaries, reducing costs. Participants can bet and claim prizes anonymously, protecting their privacy. Unlike traditional lotteries, decentralized systems are open to everyone with internet access and a crypto wallet.</p>
    },{
      title:"Why do we build on Arweave AO?",
      content: <p>The lottery is a mass-market product, allowing everyone to experience the thrill of turning small bets into big rewards. After evaluating various blockchains, we found that Arweave's AO framework provides a Web 2.0-like user experience, with key advantages like high concurrency and low transaction costs. While Ethereum charges $10-$12 per transaction, AO allows you to bet for just $1.<br/><br/>
      Arweave is a decentralized, permanent network. We’ve deployed both the smart contracts (backend) and the frontend on Permaweb, ensuring they remain accessible forever through hundreds of global Arweave gateways, enhancing accessibility. <a>Learn More</a></p>
    },{
      title: "Are the betting funds in the prize pool safe?",
      content:<p>Funds are 100% secure. All funds used for lottery purchasing are managed by an AO process (smart contract) and never go to a private wallet. The funds are automatically transferred via the contract algorithm. As this is on-chain betting, every transaction is recorded on the blockchain, making it traceable, queryable, and immutable. You can <a>click here</a> to view the balance status of the funding process.</p>
    },{
      title: "How to ensure the fairness and transparency of the lottery?",
      content: <div>
        <p>At the end of each lottery round, a three-digit lucky number (000-999) is generated using the HMAC random algorithm, ensuring verifiability as results are deterministic for the same seed. To ensure unpredictability, the seed combines three factors:</p>
        <ol class="pt-4 pl-8">
          <li class="list-decimal"><b>ArchivedID</b>: A hash digest from the round's bet snapshot, signed with the CU's private key to prevent prediction.</li>
          <li class="list-decimal"><b>Block Hash and Timestamp</b>: From the block at the draw trigger, based on blockchain transaction data. The draw occurs in the block following the round's end, making it uncontrollable.</li>
          <li class="list-decimal"><b>The Last Bet Transaction ID</b>: Generated when the final bet is submitted. After payment, the token process (contract) sends a "Credit-Notice" to the betting process, and the transaction ID is included as part of the seed.</li>
        </ol>
      </div>
    },{
      title:"What is $ALT, and what benefits does it offer?",
      content: <div>
        <p>$ALT (Ao Lotto Token) is a community-distributed token with a total supply of 210 million. It shares 100% of Aolotto ecosystem profits with $ALT holders and offers several benefits:</p>
        <ol class="pt-4 pl-8">
          <li class="list-decimal"><b>Community Governance</b>: Vote on proposals and influence development.</li>
          <li class="list-decimal"><b>Ecosystem Currency</b>: Use $ALT in games and apps within the Aolotto ecosystem.</li>
          <li class="list-decimal"><b>Charity Participation</b>: Stake $ALT to support charitable causes and earn NFT badges.</li>
          <li class="list-decimal"><b>Discover More Value</b>: Explore additional exciting use cases over time.</li>
        </ol>
        <p class="pt-4">$ALT is based on the AO standard, with partnerships like Permadao. It will soon be listed on DEXs. With its limited supply, $ALT is worth exploring further</p>
      </div>
    }
  ]))
  return (
    <main>
      <div class="container relative z-0 overflow-visible">
        <section class="py-18 response_cols">
          
          <div class="col-span-full flex items-center justify-center">
            <span class="text-6xl text-center text-balance leading-18 w-[70%]">The first decentralized <b>lottery</b> game built on AO</span>
          </div>
          <div class="col-span-full flex flex-col gap-8 items-center justify-center">
            <div class="flex flex-col justify-center items-center gap-2">
              <span class="text-current/50 uppercase">Progressive Jackpot</span>
              <span class="text-4xl text-third font-bold">
                <Show when={!state.loading} fallback="...">${toBalanceValue(state()?.jackpot, pool.denomination||6,2)}</Show>
              </span>
            </div>
            <div class="flex flex-col items-center justify-center gap-4">
              <A class="btn btn-primary btn-xl w-fit rounded-full" href="/bets">Let's bet to WIN <Icon icon="iconoir:arrow-right"/></A>
              <Show when={!state.loading} fallback="...">
                <span class="text-current/50">Round-{state()?.round || 1} , $1 on-chain betting</span>
              </Show>
            </div>
          </div>
          <div class="col-span-full flex items-center justify-center gap-2 pt-8">
            <For each={partners()}>
              {(item)=><a class="text-base-content" href={item.link} target="_blank" use:tooltip={["bottom",item.tooltip]}>{item.element}</a>}
            </For>
          </div>
        </section>
        <div class="absolute top-0 left-0 w-full -z-1">
        <Balls class="w-full"/>
        </div>
      </div>

      <div class="w-full bg-linear-to-b from-current/5 to-current/0">

      <div class="container relative z-0 overflow-visible ">
 
        <section class="py-16 border-b border-current/10 response_cols  px-2">
          <div class="col-span-full lg:col-span-4">
            <div class="uppercase text-current/50">total sold</div>
            <div class="text-3xl"><Show when={!stats.loading} fallback="...">${toBalanceValue(stats()?.total_sales_amount,pool.denomination || 6,2)}</Show></div>
            <div class="pt-4">
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Profits:</span> <span>${toBalanceValue(stats()?.taxation?.[1]+state()?.balance * 0.1,pool.denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Dividends:</span> <span>${toBalanceValue(stats()?.taxation?.[2],pool.denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Buyback & Burned:</span> <span>${toBalanceValue(stats()?.taxation?.[2],pool.denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Current Circulation:</span> <span>23</span></div>
              {/* <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Burned</span><span>2</span><span class="text-current/50">$ALT holders</span></div> */}
            </div>
            
          </div>
          <div class="col-span-full lg:col-span-7 lg:col-end-13">
            {/* <div class="text-current/50 uppercase">#Bet2Earn<Altlogo class="size-4"/></div> */}
            <h2 class="text-2xl pb-6  leading-10 flex items-center gap-2">
            LottoFi - Unlock Continuous Dividends from $ALT, Fairly Issued via Bet2Mint.
            </h2>
            <p class="text-md text-current/50">LottoFi's value is primarily driven by jackpot taxes, with 100% of profits returned to $ALT holders through dividends and buyback-to-burn. The total supply of $ALT is capped at 210 million, and anyone can earn it through the Bet2Mint mechanism. <a href="#" target="_blank" class="inline-flex items-center gap-2">Learn more <Icon icon="iconoir:arrow-right"/></a></p>
          </div>
        </section>

  
        <section class="py-16 response_cols px-2 ">
          <div class="col-span-full px-16 text-center flex flex-col justify-center items-center gap-4">
            <div class="flex items-center gap-2">
            <Show when={pool?.id}>
            <Icon icon="iconoir:component" />
                <a 
                  class="inline-flex items-center text-base-content/50" 
                  use:tooltip={["top-overlap",()=>pool.id]}
                  target="_blank"
                  href={`${app.ao_link_url}/#/entity/${pool.id}`}
                >
                  {shortStr(pool.id,6)} <Icon icon="ei:external-link"></Icon>
                </a>
              </Show>
            </div>
            
            <div class="text-3xl leading-12 ">$1 On-chain betting and drawing without human control, Simple, Permissionless and Transparent.</div>
          </div>

          <div class="col-span-full flex items-center justify-center pt-12">
            <div class="max-w-[60em] w-full gap-4 flex flex-col">
            <For each={faq()}>
              {({title,content},index)=>(
                <details class="w-full bg-current/2 hover:bg-current/5 rounded-lg border-current/5 border ">
                  <summary class="w-full flex justify-between gap-4 p-4 items-center cursor-pointer">
                    <span class="rounded-full size-6 inline-flex justify-center items-center text-current/50">{index()+1}</span>
                    <span class="flex-1 text-current/60">{title}</span>
                    <span class="text-current/50"><Icon icon="iconoir:arrow-separate-vertical"></Icon></span>
                  </summary>
                  <div class="px-6">
                  <div class="py-4 border-t border-current/10">{content}</div> 
                  </div>
                </details>
              )}
            </For>
            <div class="inline-flex justify-center items-center p-2 gap-2 mt-2">
              <a href="dd" class="inline-flex items-center">Online Support<Icon icon="ei:external-link"></Icon></a>
              <span class="text-current/50">or</span>
              <a href="dd" class="inline-flex items-center">Learn More<Icon icon="ei:external-link"></Icon></a>
            </div>
            </div>
          
          </div>
          
        </section>

      <section class="flex justify-center flex-col items-center gap-8  p-16  text-center ">
        <p class="flex items-center gap-2">
        <Icon icon="arcticons:apps" />
        <Icon icon="arcticons:games-2" />
        <Icon icon="arcticons:bookshelf" />
        <Icon icon="arcticons:leafpic" />
        </p>
        <p class="text-2xl ">Beyond a lottery — a thriving LottoFi ecosystem powered by the $ALT community.</p>
        <button class="btn btn-xl rounded-full w-fit gap-4 items-center btn-third"><Icon icon="iconoir:app-store" />Let's build together</button>
        <p class="text-current/50">LottoFi is an ecosystem of apps, games, and content publishing driven by $ALT staking. By staking $ALT, users unlock free tools or skills, while creators or developers earn dividend rewards. With the global lottery market projected to surpass $450 billion by 2025, we aim to return profits monopolized by traditional lottery issuers to the community, fostering quality content creation and strengthening community consensus.</p>
     
      </section>
      <div class="absolute bottom-0 scale-105 left-0 w-full -z-1">
        <Pattern class="w-full"/>
      </div>
      
      
    </div>
    </div>
    </main>
    
  )
}