import { Icon } from "@iconify-icon/solid"
import { A } from "@solidjs/router"
import { shortStr } from "../../lib/tool"
import { createEffect, createMemo, For, Show, Switch } from "solid-js"
import { app,protocols } from "../../signals/global"
import tooltip from "../../components/tooltip"
import { state,stats } from "../../signals/pool"
import { toBalanceValue } from "../../lib/tool"
import Balls from "../../components/balls"
import Aox from "./partners/aox"
import Permaswap from "./partners/permaswap"
import Aolink from "./partners/aolink"
import Typr from "./partners/typr"
import Seagull from "./partners/seagull"
import Pattern from "../../components/pattern"
import Altlogo from "../../components/altlogo"
import { t,setDictionarys,dictionarys } from "../../i18n"
import { redirect } from "@solidjs/router"



export default props => {
  setDictionarys("en",{
    "top.slogan": "The $1 on-chain lottery only possible on AO",
    "top.jackpot_title": "Progressive Jackpot",
    "top.button_bet": "Let's bet to WIN!",
    "top.round": "Round-{{round}}",
    "top.win_tip": "Last bet, higher win rate!",
    "second.title": "$ALT - fairly issued via Bet2Mint, unlock dividends and LottoFi benefits by holding.",
    "second.desc": "LottoFi's value is primarily driven by jackpot taxes, with 100% of profits returned to $ALT holders through dividends and buyback-to-burn. The total supply of $ALT is capped at 210 million, and anyone can earn it through the Bet2Mint mechanism.",
    "second.label_sold":"Total sold",
    "third.title": "The first decentralized lottery protocol based on AO, Simple, Permissionless and Transparent",
    "third.second_title": "Beyond a lottery — a thriving LottoFi ecosystem powered by the $ALT community",
    "third.second_desc": "LottoFi is an ecosystem of apps, games, and content publishing driven by $ALT staking. By staking $ALT, users unlock free tools or skills, while creators or developers earn dividend rewards. We aim to return profits monopolized by traditional lottery issuers to the community, fostering quality content creation and strengthening community consensus.",
    "third.build_btn" : "Let's build together",
    "partners": [
      "The largest cross-chain bridge in the AO ecosystem, AOX enables seamless payments."
    ]
  })

  setDictionarys("zh",{
    "top.slogan": "$1美元鏈上彩票在AO上成為可能",
    "top.jackpot_title": "当前累計大獎",
    "top.button_bet": "立即投注中大獎!",
    "top.round": "回合-{{round}}",
    "top.win_tip": "最後下注，贏率更高!",
    "second.title":"$ALT - 透過Bet2Mint機制公平發行,持有獲得持續性分紅, 享受LottoFi生態紅利",
    "second.desc": "向贏家徵收大獎稅奠定了LottoFi的價值根基,協議產生的利潤通過分紅和回購銷毀機制100%回饋給$ALT代幣持有者，發行總量上限為2.1億，任何人都可以通過Bet2Mint機制免費取得.",
    "second.label_sold":"累計銷售",
    "third.title": "第一個基於AO構建的去中心化彩票協議, 簡單, 無許可且公平透明",
    "third.second_title": "不只是彩票，一個繁榮的LottoFi生態將在$ALT社區的支持下持續發展",
    "third.second_desc": "LottoFi 是一個由 $ALT 質押驅動的App、遊戲和內容生態系統。透過質押ALT，用戶可以解鎖免費工具或技能，而創作者或開發者則可以獲得分紅獎勵。我們的目標是將傳統彩券發行機構壟斷的利潤回饋社区，培育優質內容創作，凝聚社區共識。",
    "third.build_btn" : "让我们一同构建",
    "partners": [
      "由AO生态最大的跨链桥AOX提供无缝的支付体验"
    ]
  })

  const pool_i = protocols?.details[protocols?.pool_id]
  const agent_i = protocols?.details[protocols?.agent_id]
  const pay_i = protocols?.details[protocols?.pay_id]

  const partners = createMemo(()=>([{
    tooltip: "The largest cross-chain bridge in the AO ecosystem, AOX enables seamless payments.",
    link: "https://aox.xyz",
    element: <Aox class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Permaswap is our strategic partner, offering DEX integration.",
    link: "https://www.permaswap.network",
    element: <Permaswap class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Aolink provides on-chain querying.",
    link: "https://www.ao.link",
    element: <Aolink class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Typr is our strategic partner, a decentralized information publishing platform like twitter.",
    link: "https://www.typr.day",
    element: <Typr class="opacity-50 h-8 hover:opacity-100"/>
  },{
    tooltip: "Seagull is a partner of our ecosystem with a focus on GameFi.",
    link: "https://x.com/happytowngame",
    element: <Seagull class="opacity-50 h-8 hover:opacity-100"/>
  }]))

  const faq = createMemo(()=>([{
    title:"How dose Aolotto work?",
    content: <div class="flex flex-col gap-4">
      <p>Aolotto is a simple lottery game where players bet $1 to choose a three-digit number (000-999). A draw occurs at the end of each round, with a lucky number generated by algorithm. bets that match the number win.</p>
      <p>Winners share the accumulated jackpot proportionally based on their bet amounts. If no matching bets are placed in a round, the last player takes the entire jackpot.</p>
      <p>The accumulated jackpot consists of 50% of pool balance, while the remaining 50% becomes the base prize for the next round.</p>
      <p>Aolotto's draw time is dynamic, Each new bet extends the draw by 24 hours until the pool's accumulated bets reach the target. When draw time arrives, the game moves to the next round, and the draw is triggered at the next block height after the round ends.</p>
    </div>
  },
    {
      title:"What is the difference between aolotto and traditional lottery?",
      content:<p>Decentralized lotteries offer <b>transparency</b>, <b>fairness</b>, and <b>global accessibility</b>. Blockchain records ensure tamper-proof draws, while smart contracts eliminate fraud and intermediaries, reducing costs. Participants can bet and claim prizes anonymously, protecting their privacy. Unlike traditional lotteries, decentralized systems are open to everyone with internet access and a crypto wallet.</p>
    },{
      title:"Why do we build on Arweave AO?",
      content: <p>The lottery is a mass-market product, allowing everyone to experience the thrill of turning small bets into big rewards. After evaluating various blockchains, we found that Arweave's AO framework provides a Web 2.0-like user experience, with key advantages like high concurrency and low transaction costs. While Ethereum charges $10-$12 per transaction, AO allows you to bet for just $1.<br/><br/>
      Arweave is a decentralized, permanent network. We’ve deployed both the smart contracts (backend) and the frontend on Permaweb, ensuring they remain accessible forever through hundreds of global Arweave gateways, enhancing accessibility. <a>Learn More</a></p>
    },{
      title: "Are the betting funds in the prize pool safe?",
      content:<p>Funds are 100% secure. All funds used for lottery purchasing are managed by an AO process (smart contract) and never go to a private wallet. The funds are automatically transferred via the contract algorithm. As this is on-chain betting, every transaction is recorded on the blockchain, making it traceable, queryable, and immutable. You can <a>click here</a> to view the balance status of the funding process.</p>
    },{
      title: "How to ensure the fairness and transparency of the lottery?",
      content: <div>
        <p>At the end of each lottery round, a three-digit lucky number (000-999) is generated using the HMAC random algorithm, ensuring verifiability as results are deterministic for the same seed. To ensure unpredictability, the seed combines three factors:</p>
        <ol class="pt-4 pl-8">
          <li class="list-decimal"><b>ArchivedID</b>: A hash digest from the round's bet snapshot, signed with the CU's private key to prevent prediction.</li>
          <li class="list-decimal"><b>Block Hash and Timestamp</b>: From the block at the draw trigger, based on blockchain transaction data. The draw occurs in the block following the round's end, making it uncontrollable.</li>
          <li class="list-decimal"><b>The Last Bet Transaction ID</b>: Generated when the final bet is submitted. After payment, the token process (contract) sends a "Credit-Notice" to the betting process, and the transaction ID is included as part of the seed.</li>
        </ol>
      </div>
    },{
      title:"What is $ALT, and what benefits does it offer?",
      content: <div>
        <p>$ALT (Ao Lotto Token) is a community-distributed token with a total supply of 210 million. It shares 100% of Aolotto ecosystem profits with $ALT holders and offers several benefits:</p>
        <ol class="pt-4 pl-8">
          <li class="list-decimal"><b>Community Governance</b>: Vote on proposals and influence development.</li>
          <li class="list-decimal"><b>Ecosystem Currency</b>: Use $ALT in games and apps within the Aolotto ecosystem.</li>
          <li class="list-decimal"><b>Charity Participation</b>: Stake $ALT to support charitable causes and earn NFT badges.</li>
          <li class="list-decimal"><b>Discover More Value</b>: Explore additional exciting use cases over time.</li>
        </ol>
        <p class="pt-4">$ALT is based on the AO standard, with partnerships like Permadao. It will soon be listed on DEXs. With its limited supply, $ALT is worth exploring further</p>
      </div>
    }
  ]))

  
 

  return (
    <main>
      <div class="container relative z-0 overflow-visible">
        <section class="py-18 response_cols">
          
          <div class="col-span-full flex items-center justify-center">
            <span class="text-6xl text-center text-balance leading-18 w-[70%] mt-16">{t("top.slogan")}</span>
          </div>
          <div class="col-span-full flex flex-col gap-8 items-center justify-center">
            <div class="flex flex-col justify-center items-center gap-2">
              <span class="text-current/50 uppercase">{t("top.jackpot_title")}</span>
              <span class="text-4xl text-third font-bold">
                <Show when={!state.loading} fallback="...">${toBalanceValue(state()?.jackpot, pay_i?.Denomination||6,2)}</Show>
              </span>
            </div>
            <div class="flex flex-col items-center justify-center gap-4">
              <A class="btn btn-primary btn-xl w-fit rounded-full" href="/bets">{t("top.button_bet")} <Icon icon="iconoir:arrow-right"/></A>
              <Show when={!state.loading} fallback="...">
                <span class="text-current/50">{t("top.round",{round:state()?.round || 1})} , {t("top.win_tip")}</span>
              </Show>
            </div>
          </div>
          <div class="col-span-full flex items-center justify-center gap-2 pt-8">
            <For each={partners()}>
              {(item,idx)=><a class="text-base-content" href={item.link} target="_blank" use:tooltip={["bottom",t(`partners[${idx()}]`)]}>{item.element}</a>}
            </For>
          </div>
        </section>
        <div class="absolute top-0 left-0 w-full -z-1">
        <Balls class="w-full"/>
        </div>
      </div>

      <div class="w-full bg-linear-to-b from-current/5 to-current/0">

      <div class="container relative z-0 overflow-visible ">
 
        <section class="py-16 border-b border-current/10 response_cols  px-2">
          <div class="col-span-full lg:col-span-4">
            <div class="uppercase text-current/50">{t("second.label_sold")}</div>
            <div class="text-3xl"><Show when={!stats.loading} fallback="...">${toBalanceValue(stats()?.total_sales_amount,pay_i?.Denomination || 6,2)}</Show></div>
            <div class="pt-4">
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Profits:</span> <span>${toBalanceValue(stats()?.total_sales_amount * 0.4,pay_i.Denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Dividends:</span> <span>${toBalanceValue(stats()?.dividends?.[2],pay_i?.Denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Buyback & Burned:</span> <span>${toBalanceValue(stats()?.buybacks?.[2],pay_i?.Denomination || 6,2)}</span></div>
              <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">$ALT Circulation:</span> <span>{toBalanceValue(stats()?.total_supply,12,0)}</span></div>
              {/* <div class="flex items-center gap-2 h-8"><Icon icon="ph:arrow-elbow-down-right-light"></Icon><span class="text-current/50">Total Burned</span><span>2</span><span class="text-current/50">$ALT holders</span></div> */}
            </div>
            
          </div>
          <div class="col-span-full lg:col-span-7 lg:col-end-13">
            {/* <div class="text-current/50 uppercase">#Bet2Earn<Altlogo class="size-4"/></div> */}
            <h2 class="text-2xl pb-6  leading-10 flex items-center gap-2">
            {t("second.title")}
            </h2>
            <p class="text-md text-current/50">{t("second.desc")}. <a href="#" target="_blank" class="inline-flex items-center gap-2">Learn more <Icon icon="iconoir:arrow-right"/></a></p>
          </div>
        </section>

  
        <section class="py-16 response_cols px-2 ">
          <div class="col-span-full px-16 text-center flex flex-col justify-center items-center gap-4">
            <div class="flex items-center gap-2">
            <Show when={protocols?.pool_id}>
            <Icon icon="iconoir:component" />
                <a 
                  class="inline-flex items-center text-base-content/50" 
                  use:tooltip={["top-overlap",()=>protocols?.pool_id]}
                  target="_blank"
                  href={`${app.ao_link_url}/#/entity/${protocols?.pool_id}`}
                >
                  {shortStr(protocols?.pool_id,6)} <Icon icon="ei:external-link"></Icon>
                </a>
              </Show>
            </div>
            
            <div class="text-3xl leading-12 ">{t("third.title")}</div>
          </div>

          <div class="col-span-full flex items-center justify-center pt-12">
            <div class="max-w-[60em] w-full gap-4 flex flex-col">
            <For each={faq()}>
              {({title,content},index)=>(
                <details class="w-full bg-current/2 hover:bg-current/5 rounded-lg border-current/5 border ">
                  <summary class="w-full flex justify-between gap-4 p-4 items-center cursor-pointer">
                    <span class="rounded-full size-6 inline-flex justify-center items-center text-current/50">{index()+1}</span>
                    <span class="flex-1 text-current/60">{title}</span>
                    <span class="text-current/50"><Icon icon="iconoir:arrow-separate-vertical"></Icon></span>
                  </summary>
                  <div class="px-6">
                  <div class="py-4 border-t border-current/10">{content}</div> 
                  </div>
                </details>
              )}
            </For>
            <div class="inline-flex justify-center items-center p-2 gap-2 mt-2">
              <a href="dd" class="inline-flex items-center">Online Support<Icon icon="ei:external-link"></Icon></a>
              <span class="text-current/50">or</span>
              <a href="dd" class="inline-flex items-center">Learn More<Icon icon="ei:external-link"></Icon></a>
            </div>
            </div>
          
          </div>
          
        </section>

      <section class="flex justify-center flex-col items-center gap-8  p-16  text-center ">
        <p class="flex items-center gap-2">
        <Icon icon="arcticons:apps" />
        <Icon icon="arcticons:games-2" />
        <Icon icon="arcticons:bookshelf" />
        <Icon icon="arcticons:leafpic" />
        </p>
        <p class="text-2xl ">{t("third.second_title")}</p>
        <button class="btn btn-xl rounded-full w-fit gap-4 items-center btn-third"><Icon icon="iconoir:app-store" />{t("third.build_btn")}</button>
        <p class="text-current/50">{t("third.second_desc")}</p>
     
      </section>
      <div class="absolute bottom-0 scale-105 left-0 w-full -z-1">
        <Pattern class="w-full"/>
      </div>
      
      
    </div>
    </div>
    </main>
    
  )
}