
import { Modal,ModalHeader,ModalContainer } from "./popup";
import { Icon } from "@iconify-icon/solid";
import { onMount } from "solid-js";
import { t,setDictionarys } from "../i18n";
export default props => {
  let _rules
  setDictionarys("en",{
    "r.a":"Choose a 3-digit number and place your bet ($1 minimum, $100 maximum).",
    "r.b":"If the total wagers for the round don't reach the target, the draw time will be extended by 24 hours with each new bet.",
    "r.c":"When the draw time arrives, a 3-digit lucky number will be generated by the algorithm. If your number matches, you'll share the jackpot with other winners (or be the sole winner if you are the only match).",
    "r.d":"If no matching bets are placed, the last bettor wins the entire jackpot.",
    "r.e":"A Bet2Mint (bet-to-mint) reward is set at the start of each round, equivalent to 1/500 of the uncirculated $ALT (with a total supply of 210 million). This reward is given to the bettors of the current round, with the reward amount for each bet based on the reward ladder.",
    "r.f":"Once the bet amount reaches the target, the draw time will be locked and will no longer be extended indefinitely. Conversely, if no new bets are placed within 24 hours after a bet, the draw will also be triggered.",
    "r.g":"The jackpot is 50% of the pool balance, while the remaining 50% carries over to the next round as the base balance of the pool. The pool grows with the total amount of bets placed. Good luck!",
    "r.h":"learn more on docs"
  })
  setDictionarys("zh",{
    "r.a":"選擇任意3位數字並下注（最低投注金额$1，最高$100）。",
    "r.b":"如果本輪的總投注金額未達到预定目標，則每次新投注都會將開獎時間延長至下注后的24小時。",
    "r.c":"當開獎時間到達時，算法將生成一個3位數的幸運號碼。如果您的號碼匹配，您將與其他中獎者分享大奖（当然如果您是唯一匹配投注，您也是唯一的中獎者）。",
    "r.d":"如果沒有匹配的投注，最後一個下注者將贏得整個大奖。",
    "r.e":"每輪启动时设置一笔Bet2Mint(投注挖矿)奖励，相當於未流通$ALT的1/500（總供應量為2.1亿），獎勵本轮的投注者，每笔投注获得的奖励额度参照奖励阶梯；",
    "r.f":"一旦投注金額達到目標，開獎時間將被锁定，不会因为新的投注增加而无限延長，反之，如果一笔投注之后24小时内无新的投注追加，也会触发开奖；",
    "r.g":"大奖金额是当前奖池总额的50%，会隨投注總額增加而增加，剩余50%保留到下一轮作为基础奖金，祝好運！",
    "r.h":"去文檔中了解更多"
  })
  onMount(()=>{
      props.ref({
        open:()=>{
          _rules.open()
        },
        close:()=>_rules.close(),
      })
    })
  return (
  
    <Modal 
      ref={_rules}
      mask={true}
      closable={true}
      class="w-full max-w-[480px]"
    >
      <ModalHeader title="The Rules"></ModalHeader>
      <ModalContainer class="w-full max-h-[85vh] overflow-y-auto">
        <div class=" m-[1em] pt-4">
          <ol class="list-decimal list-outside flex flex-col gap-4 pl-8">
            <li>{t("r.a")}</li>
            <li>{t("r.b")}</li>
            <li>{t("r.c")}</li>
            <li>{t("r.d")}</li>
            <li>{t("r.e")}</li>
            <li>{t("r.f")}</li>
            <li>{t("r.g")}</li>
          </ol>
          <div class="m-[1em] py-4 flex justify-end"><a class="flex items-center" href="https://docs.aolotto.com/en" target="_blank">{t("r.h")} <Icon icon="ei:external-link"></Icon></a></div>
        </div>
        
      </ModalContainer> 
    </Modal>
  )
}