import { InfoItem } from "../../components/infoitem"
import { shortStr } from "../../lib/tool"
import { ShareToSocial } from "../../components/share"
import { Icon } from "@iconify-icon/solid"
import { createEffect, Suspense } from "solid-js"
import Spinner from "../../components/spinner"
import Draws from "./draws"
import { stats } from "../../signals/pool"
import { currency } from "../../signals/global"
import { toBalanceValue } from "../../lib/tool"


export default props => {
  createEffect(()=>console.log(stats()))
  return (
    <div class="container flex-col flex gap-12 py-16 min-h-lvh/2">
       
      <section class="response_cols">
        <div class="col-span-full lg:col-span-5 flex flex-col">
          <InfoItem label={"Total Draws"}>{stats()?.total_archived_round} <span class="text-current/50">{stats()?.total_archived_round>1?"Rounds":"Round"}</span></InfoItem>
          <InfoItem label={"Total Rewarded"}>{toBalanceValue(stats()?.total_reward_amount,6,2)} <span class="text-current/50">${currency.ticker}</span></InfoItem>
          <InfoItem label={"Total Winners"}>{stats()?.total_winners} <span class="text-current/50">{stats()?.total_winners>1?"Players":"Player"}</span></InfoItem>
        </div>

        <div class="col-span-full lg:col-span-4 lg:col-end-13">

          <div class="text-current/50">
            The winning number are generated by a random algorithm, which is fair and transparent. <a href="#" target="_blank" class="inline-flex items-center gap-2">Learn More<Icon icon="ei:external-link"></Icon></a>
          </div>
        </div>
        
      </section>
      <Suspense fallback={<Spinner/>}>
        <Draws/>
      </Suspense>
      

      {/* <section class="response_cols border-y border-current/20 py-12 px-1">
        <div class="col-span-full lg:col-span-2">
          <span class="text-2xl">R2</span>
        </div>
        <div class="col-span-full lg:col-span-6 flex flex-col gap-4">
          <InfoItem label={"Lucky Numbers"}>
            <div class="flex items-center gap-2">
              <span class="inline-flex gap-2">
                <span class="ball ball-fill">1</span>
                <span class="ball ball-fill">2</span>
                <span class="ball ball-fill">3</span>
              </span>
              <span class="text-current/50">0 Matched</span>
            </div>
          </InfoItem>
          <InfoItem label={"Total Rewards"}><span>$23450.00</span> <span class="text-current/50">$USDC</span></InfoItem>
          <InfoItem label={"Winners"}>8 players</InfoItem>
          <InfoItem label={"Drawing Id"}>{shortStr("9FbwODwBT7M-Ym8GlZNXPMq4KHEYMn0ZGmjsrcuF7ho",6)} <Icon icon="ei:external-link"></Icon></InfoItem>
        </div>
        <div class="col-span-full lg:col-span-4">
          <div class="flex justify-between">
            <span class="text-current/50">2024/11/11 11:00:00</span>
            <ShareToSocial/>
          </div>
        </div>
      </section>

      <section>
        <div class="w-full flex items-center justify-between px-2">
        <iconify-icon icon="iconoir:arrow-left"></iconify-icon>
        <span>1 2 3</span>
        <iconify-icon icon="iconoir:arrow-right"></iconify-icon>
        </div>
      </section> */}

    </div>
  )
}