name: publish to permaweb

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run deploy-main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          VITE_APP_NAME: Aolotto
          VITE_AGENT_PROCESS: eGPZS8D1Ck_CpWxPr6JqUUJerFrODoXn7uqL_GJGnBg
          VITE_PAY_PROCESS : 7zH9dlMNoxprab9loshv3Y7WG45DOny_Vrq9KrXObdQ
          VITE_POOL_PROCESS : 7vTXHQK2yJJHDwFyJRSoXXU5fF4FQYLd8PjTNlHpVj0
          VITE_FAUCET_PROCESS : d7rD_KozquZU8T5nDoBngFpnW2Qk6WeNTAaTER8RX6c
          VITE_FUNDATION_PROCESS : 3JLHNobQvmwjhb-wVmcj0dukyVHgBHAbg8L8hZc0LpA
          VITE_BUYBACK_PROCESS : ntlTMR1pEt6dyRrfy2rdAeQI90LlO8eXK8N-wB68Ft0
          VITE_STAKE_PROCESS : kqDiKjXCwO16RJmjJqSNDbqdMVbrCaplEh7KnUHinlA
          VITE_ALT_WUSDC_PROCESS : 2sWVPeUTYuB0VMrkgC9m_0MwljaZqEJdAfgJXNZgEIw
          VITE_ALT_PROCESS : 3IYRZBvph5Xx9566RuGWdLvUHnOcG8cHXT95s1CYRBo
          VITE_LAUNCH_TIME: 1735689601000
          VITE_GATEWAY_URL: https://arweave.net
          VITE_GATEWAY: arweave.net
          VITE_GQL_ENDPOINT: https://arweave-search.goldsky.com/graphql
          VITE_MU_URL:https: //mu.ao-testnet.xyz
          VITE_CU_URL:https: //cu.ao-testnet.xyz
          VITE_SCHEDULER: _GQ33BkPtZrqxA84vM8Zk-N2aO0toNNu_C-l-rawrBA
          VITE_AO_LINK: https://www.ao.link
          VITE_AO_MODULE: Do_Uc2Sju_ffp6Ev0AnLVdPtot15rvMjP-a9VVaA5fM


          
